spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: never

  batch:
    jdbc:
      initialize-schema: never

batch:
  scheduler:
    cron: "0 0 0 * * *" # 매일 자정 실행, 필요시 값 조정

user:
  cleanup:
    cron: "0 50 23 * * *"