package com.team3.deokhugam.global.lock.domain;

public enum LockName {
  // 회원가입, 회원탈퇴
  USER_REGISTER,
  USER_WITHDRAWAL,

  BOOK_CREATE,

  REVIEW_CREATE,
  REVIEW_LIKE_TOGGLE,

  COMMENT_CREATE,
  COMMENT_DELETE,

  // 배치 작업
  POPULAR_BOOK_BATCH,
  POPULAR_REVIEW_BATCH,
  POWER_USER_BATCH,
  USER_CLEANUP_BATCH,
  NOTIFICATION_CLEANUP_BATCH,
  APPLICATION_LOCK_CLEANUP_BATCH
}
